# Generated by Django 5.2 on 2025-04-30 09:15

import autoslug.fields
import lang_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lang_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='y', editable=False, populate_from=lang_app.models.blog_slug_populate, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courselesson',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='y', editable=False, populate_from=lang_app.models.lesson_slug_populate, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='y', editable=False, populate_from=lang_app.models.module_slug_populate, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrolledcourses',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='y', editable=False, populate_from=lang_app.models.enroll_slug_populate, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='y', editable=False, max_length=255, populate_from=lang_app.models.post_slug_populate, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=lang_app.models.course_slug_populate, unique=True),
        ),
    ]
