# Generated by Django 5.2 on 2025-04-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang_app', '0002_myuser_display_name_alter_myuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='device_info',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
