# Generated by Django 5.2 on 2025-04-30 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lang_app', '0002_blog_slug_courselesson_slug_coursemodule_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselesson',
            name='lesson_title',
        ),
    ]
