# Generated by Django 5.2 on 2025-04-24 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lang_app', '0003_myuser_city_myuser_device_info'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
            ],
        ),
    ]
