# Generated by Django 5.2 on 2025-04-30 10:17

import autoslug.fields
import lang_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang_app', '0003_remove_courselesson_lesson_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolledcourses',
            name='progress',
        ),
        migrations.AddField(
            model_name='enrolledcourses',
            name='is_enrolled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from=lang_app.models.blog_slug_populate, unique=True),
        ),
    ]
