# Generated by Django 5.2 on 2025-04-30 13:31

import autoslug.fields
import lang_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lang_app', '0004_remove_enrolledcourses_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='user', editable=False, max_length=255, populate_from=lang_app.models.user_slug_populate, unique=True),
            preserve_default=False,
        ),
    ]
