# Generated by Django 5.2 on 2025-04-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang_app', '0005_course_blog_coursemodule_courselesson_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_author',
            field=models.CharField(max_length=255),
        ),
    ]
