# Generated by Django 5.2 on 2025-04-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang_app', '0006_alter_blog_blog_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['difficulty']},
        ),
        migrations.AddField(
            model_name='course',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=255),
        ),
    ]
