# Generated by Django 5.2 on 2025-05-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang_app', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselesson',
            name='lesson_completed',
            field=models.BooleanField(default=False),
        ),
    ]
