# Generated by Django 5.2 on 2025-04-26 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lang_app', '0007_alter_course_options_course_difficulty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_thumbnail',
        ),
    ]
