# Generated by Django 5.2 on 2025-04-27 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang_app', '0008_remove_course_course_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['course_name', 'difficulty']},
        ),
        migrations.AddField(
            model_name='enrolledcourses',
            name='course_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_difficulty', to='lang_app.course'),
        ),
        migrations.AlterField(
            model_name='enrolledcourses',
            name='progress',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
