# Generated by Django 5.2 on 2025-04-27 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lang_app', '0009_alter_course_options_enrolledcourses_course_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolledcourses',
            name='course_level',
        ),
    ]
