# Generated by Django 5.2 on 2025-04-27 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang_app', '0010_remove_enrolledcourses_course_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolledcourses',
            old_name='course',
            new_name='course_name',
        ),
        migrations.AlterUniqueTogether(
            name='enrolledcourses',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='enrolledcourses',
            name='course_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses_difficulty', to='lang_app.course'),
        ),
        migrations.AlterUniqueTogether(
            name='enrolledcourses',
            unique_together={('student', 'course_name', 'course_level')},
        ),
    ]
