# Generated by Django 5.2 on 2025-04-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang_app', '0011_rename_course_enrolledcourses_course_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledcourses',
            name='course_level',
            field=models.CharField(max_length=255),
        ),
    ]
