# Generated by Django 5.2 on 2025-04-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang_app', '0012_alter_enrolledcourses_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledcourses',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
