# Generated by Django 5.2 on 2025-04-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang_app', '0013_enrolledcourses_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodule',
            name='course_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=255),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='module_order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='enrolledcourses',
            name='course_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=255),
        ),
    ]
