# Generated by Django 5.2 on 2025-04-27 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lang_app', '0014_coursemodule_course_level_coursemodule_module_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodule',
            name='course_level',
        ),
    ]
