# Generated by Django 5.2 on 2025-04-27 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang_app', '0015_remove_coursemodule_course_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_modules', to='lang_app.enrolledcourses'),
        ),
    ]
