# Generated by Django 5.2 on 2025-04-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang_app', '0016_alter_coursemodule_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodule',
            name='course_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=255),
        ),
    ]
