# Generated by Django 5.2 on 2025-04-28 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang_app', '0017_coursemodule_course_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodule',
            name='course_level',
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_modules', to='lang_app.course'),
        ),
    ]
